baseurl: 'http://example.org/'
languageCode: en-us
title: B.Q. Zhan
theme: hugo-ivy
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
preserveTaxonomyNames: true
footnotereturnlinkcontents: ↩

permalinks:
  note: /note/:year/:month/:day/:slug/
  post: /post/:year/:month/:day/:slug/

menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "About"
      url: "/about/"
      weight: 2
    - name: "Posts"
      url: "/post/"
      weight: 3
    - name: "Categories"
      url: "/categories/"
      weight: 4
    - name: "Tags"
      url: "/tags/"
      weight: 5

params:
  description: "A Ph.D candidate from HIT. "
  footer: "&copy; [Baoqiang Zhan](https://yihui.org) 2022 | [Github](https://github.com/bqzhan)"
  highlightjsCDN: "//cdn.bootcss.com"
  highlightjsLang: ["r", "yaml", "tex"]
  highlightjsTheme: "github"
  highlightjsVersion: "9.12.0"

markup:
  goldmark:
    renderer:
      unsafe: true

publishDir: "docs"
