baseurl: 'http://example.org/'
languageCode: en-us
title: B. Zhan
theme: hugo-ivy
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
preserveTaxonomyNames: true
footnotereturnlinkcontents: ↩

permalinks:
  note: /note/:year/:month/:day/:slug/
  post: /post/:year/:month/:day/:slug/

menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "Vitae"
      url: "/about/"
      weight: 2
    - name: "Posts"
      url: "/post/"
      weight: 3
    - name: "中文"
      url: "/note/"
      weight: 4
    - name: "Categories"
      url: "/categories/"
      weight: 5
    - name: "Tags"
      url: "/tags/"
      weight: 6

params:
  description: "A Ph.D. candidate from HIT. "
  footer: "&copy; [Baoqiang Zhan](https://bqzhan.github.io/) 2022 | [Github](https://github.com/bqzhan)"
  highlightjsCDN: "//cdn.bootcss.com"
  highlightjsLang: ["r", "yaml", "tex"]
  highlightjsTheme: "github"
  highlightjsVersion: "9.12.0"

markup:
  goldmark:
    renderer:
      unsafe: true

publishDir: "docs"
